spring:
  datasource:
    url: jdbc:mysql://192.168.99.101:32779/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  global-config:
    id-type: 0